mtime = 1599477768
[[pkgs]]
type = "github"
distrib = "e-json-encoder"
package = "e_json_encoder-1.0.2-py3-none-any"
ext = "whl"
sha256 = "352466fbf29ca5bf6fb048960adf1f6176f92f6c1fa7a2cfe866817ce7f129d2"
url = "https://api.github.com/repos/gmp2/trial_pywharf/releases/assets/25088246"

[pkgs.meta]
name = "e-json-encoder"
version = "1.0.2"
filetype = "bdist_wheel"
pyversion = "py3"
metadata_version = "2.1"
summary = "JSON Encoder allows you to recursively convert classes to json files and vice versa."
home_page = "https://github.com/embention/sw-Python_libs"
author = "Embention"
author_email = "alex.delgado@embention.com"
maintainer = ""
maintainer_email = ""
license = "Proprietary"
description = "# JSON Encoder\n\nJSON Encoder allows you to recursively convert classes to json files and vice versa.\n\n### METHODS\n\n - to_dict()\n - dumps()\n - dump(output_file_path)\n - loads(input_file_path)\n\n"
keywords = ""
platform = "UNKNOWN"
classifiers = "Programming Language :: Python :: 3"
download_url = ""
comment = ""
md5_digest = "cf4c7efa6d0e69e948ea955a618bbc93"
sha256_digest = "352466fbf29ca5bf6fb048960adf1f6176f92f6c1fa7a2cfe866817ce7f129d2"
blake2_256_digest = "366b3ecd80b38b9bac1a78775ed515cfcd79626a20f903128e94edcb6a0d86f3"
requires_python = ">=3.7"
description_content_type = "text/markdown"
":action" = "file_upload"
protocol_version = "1"
distrib = "e-json-encoder"
sha256 = "352466fbf29ca5bf6fb048960adf1f6176f92f6c1fa7a2cfe866817ce7f129d2"
